### ISSUE TITLE
Enable ACL swithc on/off in nomad

### ISSUE THREAD

**Issue by m88614** [fredrikhgrelland/vagrant-hashistack#27] opened 2020-06-16 06:38 UTC

**Comment by m88614** [comment] 2020-06-16 08:18
What do we do with the token from the acl bootstrap before we have vault? Should we simply enable ACLs at this point, then manually do the bootstrap by SSHing in, and manually saving the secret_ID/add an anonymous policy?

**Comment by zhenik** [comment] 2020-06-16 08:33
Is this issue duplicate of #8 ?

**Comment by m88614** [comment] 2020-06-16 08:40
Hm, that's a fair question. I didn't think it was intially. I'm thinking of this as a first step, then in #8 we add the option to toggle it via some config-file of sorts.

**Comment by zhenik** [comment] 2020-06-16 14:15
Let us continue in this thread.

I see several options on how to enable ACL conditionally.
1. `vagrant-hashicorp` repo
Conditional configuration at `vagrant up`, via [ENV or ALIAS](https://gist.github.com/DonRichards/8daab90879ec47d7b622ff0702e545d4)
// todo: I will provide an example later
2. Modules which use vagrant e.g.`docker-hive`
Conditional configuration via `ANSIBLE_ARGS`, [draft PR example](https://github.com/zhenik/docker-hive/pull/1)

**Comment by m88614** [comment] 2020-06-17 07:56
In both cases we need to pass this on to terraform. Terraform does not fail if it has an empty secret_id, but will obviously fail if it tries to access something that does not exist in vault. 
A solution like below would work, as long as there is an environment variable `TF_VAR_acl_enabled` terraform will use that to set `acl_enabled`. 

```
variable "acl_enabled" {
  type = bool
}

provider "nomad" {
  address = "http://127.0.0.1:4646"
  secret_id = var.acl_enabled ? "${<vault fetch token>}" : ""
}
```

in option 1 the variable need to be prefixed `TF_VAR_`, in option 2 we could have an ansible task that sets a `TF_VAR_` environment variable. Option 2 is more explicit, and easier to understand, while option 1 is shorter and less hoops to jump through. 
I like option 2, because using `TF_VAR_acl_enabled` in the vagrantfile is confusing.

**Comment by m88614** [comment] 2020-06-24 10:18
Putting this on hold while working on issues for milestone 0.2. some initial testing ad POC'ing in m88614/play/acl-nomad

**Closed** 2020-07-23 08:56 UTC
Labels: enhancement
